import os

CONFIG_FOLDER_PATH = "config"

BOT_CONFIG_FILE_NAME = "bot.config.json"
SERVER_CONFIG_FILE_NAME = "server.config.json"
MCRCON_CONFIG_FILE_NAME = "mcrcon.config.json"

BOT_CONFIG_FILE_PATH = os.path.join(CONFIG_FOLDER_PATH, BOT_CONFIG_FILE_NAME)
SERVER_CONFIG_FILE_PATH = os.path.join(CONFIG_FOLDER_PATH, SERVER_CONFIG_FILE_NAME)
MCRCON_CONFIG_FILE_PATH = os.path.join(CONFIG_FOLDER_PATH, MCRCON_CONFIG_FILE_NAME)
